# Generated by Django 5.1.2 on 2024-10-31 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('viral_load', models.FloatField()),
                ('cd4_count', models.FloatField()),
                ('adherence_level', models.CharField(max_length=50)),
                ('sequence_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('clinician', 'Clinician'), ('data_scientist', 'Data Scientist')], max_length=50)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_response', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation', to='app.patientrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_response', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_data', to='app.patientrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_response', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_result', to='app.patientrecord')),
            ],
        ),
    ]
