# Generated by Django 5.1.2 on 2024-11-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='treatment_response',
            field=models.CharField(default='Non-Responder', max_length=50),
        ),
    ]
