# Generated by Django 5.1.2 on 2024-11-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patientrecord_treatment_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
