# Generated by Django 5.1.2 on 2024-11-01 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_patientrecord_age_alter_patientrecord_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpretation',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='interpretation',
            name='predicted_response',
        ),
        migrations.AddField(
            model_name='interpretation',
            name='explanation',
            field=models.TextField(blank=True, help_text="Brief explanation of the model's prediction reason.", null=True),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='feature_importance',
            field=models.TextField(blank=True, help_text="Feature importance scores for the model's prediction.", null=True),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(help_text='Detailed diagnosis or prescription for the patient.')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='app.patientrecord')),
            ],
        ),
    ]
