# Generated by Django 5.1.2 on 2024-11-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_interpretation_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretation',
            name='lime_image',
            field=models.ImageField(blank=True, null=True, upload_to='app/int_images/lime_explanations/'),
        ),
    ]
