# Generated by Django 5.1.2 on 2024-11-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_interpretation_lime_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackData',
        ),
    ]
