# Generated by Django 5.1.2 on 2024-11-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_patientrecord_strain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='adherence_level',
            field=models.FloatField(max_length=50),
        ),
    ]
