# Generated by Django 5.1.2 on 2024-11-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_patientrecord_adherence_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpretation',
            name='feature_importance',
        ),
        migrations.AddField(
            model_name='interpretation',
            name='attention_image',
            field=models.ImageField(blank=True, null=True, upload_to='app/int_images/attention_weights/'),
        ),
    ]
