# Generated by Django 5.1.2 on 2024-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_interpretation_feature_importance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretation',
            name='attention_image2',
            field=models.ImageField(blank=True, null=True, upload_to='app/int_images/attention_weights2/'),
        ),
    ]
